set -g base-index 1

# TODO: don't work
# set-window-option -g mode-keys vi
# set -g mode-keys vi

# https://github.com/basecamp/omarchy/discussions/4899
# Smart pane switching with awareness of Vim splits.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

# Enable native tmux movements while in copy-mode
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

bind C-l send-keys 'C-l'

bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5
bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5

set-option -sg escape-time 10
set-option -g focus-events on
set-option -ag terminal-overrides ",xterm-256color:RGB"

set -g status-style fg=terminal,bg=terminal

set -g allow-passthrough on
set -g set-clipboard on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# https://www.youtube.com/shorts/PL1EoKjy4iM
# setw -g mode-keys vi
# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R
# bind-key -r C-h select-window -t :-
# bind-key -r C-l select-window -t :+
#
# unbind r
# bind r source-file ~/.tmux.conf
#
# set -g @plugin 'tmux-plugins/tpm'
#
# set -g @plugin 'catppuccin/tmux#v2.1.3'
#
# set -g @plugin 'dracula/tmux'
# set -g @dracula-show-powerline true
# set -g @dracula-cpu-display-load true
# set -g @dracula-cpu-usage-label " "
# set -g @dracula-ram-usage-label " "
# # set -g @dracula-fixed-location "Sarov"
# # set -g @dracula-plugins "weather"
# # set -g @dracula-show-fahrenheit false
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session
# set -g status-position bottom
#
# run '~/.tmux/plugins/tpm/tpm'

# unbind Space

run '~/.tmux/plugins/tpm/tpm'
