PENNYKIT_THEME_NAME="catppuccin"
PENNYKIT_THEME_WEZTERM_LINUX="Catppuccin Mocha"
PENNYKIT_THEME_WEZTERM_MACOS="Catppuccin Mocha"
PENNYKIT_THEME_BAT="catppuccin-mocha"
PENNYKIT_THEME_YAZI="yazi-rs/flavors:catppuccin-mocha"
PENNYKIT_THEME_VIVID="catppuccin-mocha"
PENNYKIT_THEME_HARLEQUIN="catppuccin-mocha"
PENNYKIT_THEME_NVIM="catppuccin"
PENNYKIT_THEME_LAZYGIT_BORDER="blue"
PENNYKIT_THEME_TMUX="catppuccin"
PENNYKIT_THEME_OMB="duru"
PENNYKIT_THEME_OMZ="robbyrussell"
PENNYKIT_THEME_LF="34"
