PENNYKIT_THEME_NAME="nord"
PENNYKIT_THEME_WEZTERM_LINUX="Nord"
PENNYKIT_THEME_WEZTERM_MACOS="Nord"
PENNYKIT_THEME_BAT="Nord"
PENNYKIT_THEME_YAZI="yazi-rs/flavors:nord"
PENNYKIT_THEME_VIVID="nord"
PENNYKIT_THEME_HARLEQUIN="nord"
PENNYKIT_THEME_NVIM="nord"
PENNYKIT_THEME_LAZYGIT_BORDER="cyan"
PENNYKIT_THEME_TMUX="minimal"
PENNYKIT_THEME_OMB="nord"
PENNYKIT_THEME_OMZ="nord"
PENNYKIT_THEME_LF="36"
