PENNYKIT_THEME_NAME="tokyonight"
PENNYKIT_THEME_WEZTERM_LINUX="Tokyo Night"
PENNYKIT_THEME_WEZTERM_MACOS="Tokyo Night"
PENNYKIT_THEME_BAT="tokyonight"
PENNYKIT_THEME_YAZI="yazi-rs/flavors:tokyonight"
PENNYKIT_THEME_VIVID="tokyonight"
PENNYKIT_THEME_HARLEQUIN="tokyonight"
PENNYKIT_THEME_NVIM="tokyonight-night"
PENNYKIT_THEME_LAZYGIT_BORDER="blue"
PENNYKIT_THEME_TMUX="minimal"
PENNYKIT_THEME_OMB="tonight"
PENNYKIT_THEME_OMZ="tonight"
