ARG PK_BASE_IMAGE_NAME=debian
ARG PK_BASE_IMAGE_TAG=trixie

FROM ${PK_BASE_IMAGE_NAME}:${PK_BASE_IMAGE_TAG}

ARG UID=1000
ARG USER=user

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Base deps
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
  build-essential  \
  ca-certificates \
  curl \
  dialog \
  file \
  git \
  locales-all \
  procps \
  sudo \
  wget && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Add non-root user
RUN groupadd --gid "${UID}" "${USER}" && \
  useradd --uid "${UID}" --gid "${UID}" --shell /bin/bash --create-home "${USER}" && \
  echo "${USER} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ${USER}
ARG HOME=/home/${USER}
WORKDIR ${HOME}

ENV LANG=ru_RU.UTF-8 \
  LANGUAGE=ru_RU:ru \
  LC_ALL=ru_RU.UTF-8

COPY --chown="${USER}:${USER}" . "${HOME}/.pennykit"

WORKDIR "${HOME}/.pennykit"

ENV PENNYKIT_HOME="${HOME}/.pennykit"

RUN "./scripts/package_installer.sh" apt
RUN "./scripts/package_configure.sh"

RUN mkdir -p "${HOME}/.config" && \
  ln -s "${HOME}/.pennykit/nvim-starter/astronvim_v6" "${HOME}/.config/nvim"

RUN nvim --headless -c 'Lazy install' -c 'qa'
# RUN nvim --headless -c 'TSInstall css html javascript latex norg scss svelte tsx typst vue regex' -c 'qa'

# RUN echo "source ${HOME}/.pennykit/pennykit.bash" >> "${HOME}/.bashrc"

WORKDIR "${HOME}"
