FROM debian:bookworm

RUN apt-get update && \
apt-get upgrade -y && \
apt-get install \
  -y --no-install-recommends \
  curl wget git ca-certificates && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*
